name: Test
on:
  push:
    branches:
      - main

env:
  OMP_NUM_THREADS: '1'
jobs:
  light_test:
    container:
      credentials:
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        username: ${{ secrets.DOCKERHUB_USERNAME }}
      image: docker://ulissigroup/kubeflow_vasp:amptorch_ocp
      volumes:
        - /home/jovyan/shared-scratch:/home/jovyan/shared-scratch
    name: Test
    runs-on:
      - self-hosted
      - linux
      - shared-scratch
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: start-measurement
      - name: Checkout actions
        uses: actions/checkout@v2
      - name: Set up environment
        run: 'export CWD=$(pwd)

          cd $CWD

          git clone https://github.com/Open-Catalyst-Project/ocp

          cd $CWD/ocp

          python setup.py develop

          cd $CWD

          '
      - id: measurement-3
        name: Record Measurement After Set up environment
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Set up environment
          task: get-measurement
      - name: Run pytest on light test suite unit tests
        run: 'pytest finetuna/tests/suites/light_suite.py -s

          '
      - id: measurement-5
        name: Record Measurement After Run pytest on light test suite unit tests
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Run pytest on light test suite unit tests
          task: get-measurement
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption-${{
          github.run_id }}.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption-${{ github.run_id }}.json
